stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker compose -p mpotap-javascript build --no-cache
    - docker compose -p mpotap-javascript up --remove-orphans --detach
