services:
  web:
    build: .
    container_name: mpotap-javascript
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - a4
      - a5
      - a6
      - a7
  a4:
    build: ./A4
    container_name: mpotap-javascript-a4
    restart: unless-stopped
  a5:
    build: ./A5
    container_name: mpotap-javascript-a5
    restart: unless-stopped
  a6:
    build: ./A6
    container_name: mpotap-javascript-a6
    restart: unless-stopped
    volumes:
      - a6-data:/app/data
  a7:
    build: ./A7
    container_name: mpotap-javascript-a7
    restart: unless-stopped

volumes:
  a6-data:
