services:
  web:
    build: .
    container_name: mpotap-javascript
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - a4
  a4:
    build: ./A4
    container_name: mpotap-javascript-a4
    restart: unless-stopped
